version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 client/main.py
    links:
      - db
    env_file:
      - .env

  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume:/data/db
    env_file:
      - .env

volumes:
  mongo_volume:
