version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 client/main.py
    links:
      - tango
      - sierra
    env_file:
      - .env

  tango:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - tango_mongo_volume:/data/db
    env_file:
      - .env

  sierra:
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - sierra_mongo_volume:/data/db
    env_file:
      - .env

volumes:
  tango_mongo_volume:
  sierra_mongo_volume:
